Exception Handling in Python
try .. except .. Finally

try - tries a piece of code
except - if an error occurs, an exception is raised according to the type of error and handles it accordingly
After which the rest of the code is terminated
Finally - overrides the termination of code, making it so after an exception is raised, another action happens instead
of the code stopping

Difference Between TypeError And ValueError is:

IndexError